# Generated by Django 5.0.6 on 2024-06-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_customuser_program_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reg_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
