# Generated by Django 5.0.6 on 2024-06-12 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_customuser_reg_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='level',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reminder',
            name='due_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SavedReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
