# Generated by Django 5.0.6 on 2024-06-12 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_customuser_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedreminder',
            name='due_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='savedreminder',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
