# Generated by Django 5.0.6 on 2024-06-14 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
