# Generated by Django 5.0.6 on 2024-06-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_reminder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
